zwLibraryManager/Library/Library/urls.py
from django.conf.urls import url,include,patterns
from django.contrib import admin
from Library import settings
from django.conf.urls.static import static

from django.conf.urls.static import static
from django.contrib.staticfiles import views
from django.views.generic import RedirectView


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'',include('management.urls')),
]
if settings.DEBUG:
	urlpatterns += [
	#url(r'^static/(?P<path>.*)$', views.static.serve, {'document_root': settings.STATIC_ROOT},     name="static"),
	url(r'^myapp/', include('myapp.urls')),
	url(r'^media/(?P<path>.*)$', views.static.serve, {'document_root': settings.MEDIA_ROOT}, name="media"),
     ]
	urlpatterns += patterns(
		url(r'^$', RedirectView.as_view(url='/myapp/list/')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

zwLibraryManager/Library/management/urls.py
# -*- coding:utf-8 -*-
from django.conf.urls import url,include
from management import views,models

urlpatterns=[
    url(r'^edit/(?P<id>\d+)/$',views.edit,name='edit_book'),
    url(r'^view_book_list/$',views.view_book_list,name='view_book_list'),
    url(r'^login/$',views.user_login,name='login'),
    url(r'^logout/$',views.user_logout,name='logout'),
    url(r'^set_password/$',views.set_password,name='set_password'),
    url(r'^add_book/$',views.add_book,name='add_book'),
    url(r'add_image/$',views.add_image,name='add_image'),
    #url(r'^view_book_list/$',views.view_book_list,name='view_book_list'),
    url(r'^book/detail/$',views.detail,name='detail'),
    url(r'^register/$',views.user_register,name='register'),
    url(r'^$',views.index,name='homepage'),
    #url(r'^edit/$',views.edit,name='edit_book'),

    # url 已经完成，接下来就是对应模板的编写了

]

zwLibraryManager/Library/myapp/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url

urlpatterns = patterns('myapp.views',
    url(r'^list/$', 'list', name='list'),
)

zwLibraryManager/Library/management/models.py
# -*- coding:utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse

# Create your models here.

# 自己需要看一下用 abstractuser 来集成的方法
class MyUser(models.Model):
    user = models.OneToOneField(User)
    # 额，暂时用数字来代替 permission
    permission = models.IntegerField(default=1)

    def __str__(self):
        return self.user.username


class Book(models.Model):
    name = models.CharField(max_length=128)
    pub_date = models.DateField()
    price = models.FloatField()
    author = models.CharField(max_length=128)
    category = models.CharField(max_length=128)
    def get_absolute_url(self):
        return reverse('edit_book',args=[self.id])
	#return HttpResponseRedirect())

    def __str__(self):
        return self.name


class Image(models.Model):
    name = models.CharField(max_length=128)
    description = models.CharField(max_length=128)
    image = models.ImageField(upload_to='images')
    book = models.ForeignKey(Book)
    #book = models.ManyToManyField(Book)

    def __str__(self):
        return self.name

zwLibraryManager/Library/management/forms.py
# -*- coding:utf-8 -*-

from .models import MyUser,Book,Image
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit

class addBookForm(forms.ModelForm):

    class Meta:
        model=Book
        fields=['name','pub_date','price','author','category']

class addImageForm(forms.ModelForm):
    '''
    name=forms.CharField(max_length=128,label="name")
    description=forms.CharField(max_length=128,label='description')
    image=forms.ImageField(label='image')
    book=forms.ChoiceField(label='book')
    '''
    class Meta:
        model=Image
        fields='__all__'




class loginForm(forms.Form):

    username=forms.CharField(max_length=128,label="username")
    password=forms.CharField(max_length=128,label="password")
    some=forms.CharField(max_length=128,required=False)
    # 不太确定是否可以这样做，sigh
    '''

    def __init__(self,*args,**kwargs):
        super(loginForm,self).__init__(*args,**kwargs)
        self.helper=FormHelper()
        self.helper.form_method='post'
        self.helper.form_action='/homepage/'
        self.helper.add_input(Submit('submit','Submit'))
    '''

class registrationForm(forms.Form):
    # 进行注册的时候要用到
    # 这个主要就在于理顺逻辑关系
    email=forms.EmailField()
    username=forms.CharField(max_length=128)
    password=forms.CharField(max_length=128)
    password_repeat=forms.CharField(max_length=128)

class BookEditForm(forms.ModelForm):
	class Meta:
		model = Book
		fields = ('name', 'pub_date', 'author', 'category', 'price')
class ImageEditForm(forms.ModelForm):
	class Meta:
		model = Image
		fields = ('name','description','image','book')

class setPasswordForm(forms.Form):
    # 进行重新设置密码
    password_old=forms.CharField(max_length=128)
    password_new=forms.CharField(max_length=128)
    password_repeat=forms.CharField(max_length=128)

zwLibraryManager/Library/management/views.py
# -*- coding:utf-8 -*-
# 这可以说是在整个过程中最有挑战性的一部分了


from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.models import User

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.urlresolvers import reverse, reverse_lazy

from .forms import setPasswordForm, registrationForm, loginForm, addBookForm, addImageForm,BookEditForm,ImageEditForm
from .models import MyUser, Book, Image
from .utils import permission_check


def index(request):
    if request.user.is_authenticated():
        user = request.user
    else:
        user = None

    context = {
        'user': user,
    }

    return render(request, 'management/index.html', context)


# 进行有关注册的部分
def user_register(request):
    if request.user.is_authenticated():
        return HttpResponseRedirect(reverse('homepage'))
    state = 'None'
    if request.method == 'POST':
        form = registrationForm(request.POST)
        if form.is_valid():
            # 把验证信息用 jquery_ui 来进行验证是更好的选择？
            username = form.cleaned_data.get('username')
            email = form.cleaned_data.get('email')
            password = form.cleaned_data.get('password')

            new_user = User.objects.create_user(username=username,
                                                email=email,
                                                password=password)
            new_user.save()
            new_myuser = MyUser(user=new_user)
            new_myuser.save()
    else:
        form = registrationForm()

    context = {
        'state': state,
        'form': form,
    }
    return render(request, 'management/register.html', context)


# 进行有关登陆的部分
def user_login(request):
    if request.user.is_authenticated():
        return HttpResponseRedirect(reverse('homepage'))
    state = None

    if request.method == 'POST':
        form = loginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)

            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse('homepage'))
            else:
                state = 'not exist or password error'
    else:
        form = loginForm()

    context = {
        'state': state,
        'user': None,
        'form': form
    }
    return render(request, 'management/login.html', context)


@login_required()
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('homepage'))


# 关于用户重新设置密码的一些问题
@login_required
def set_password(request):
    user = request.user
    state = None
    if request.method == 'POST':
        form = setPasswordForm(request.POST)
        if form.is_valid():
            old_password = form.cleaned_data.get('password_old')
            new_password = form.cleaned_data.get('password_new')
            repeat_password = form.cleaned_data.get('password_repeat')

            if user.check_password(old_password):
                if not new_password:
                    state = 'new password not exist'
                elif new_password != repeat_password:
                    state = 'not equal'
                else:
                    user.set_password(new_password)
                    user.save()
                    state = 'success'
                    # 我个人感觉这里应该？？？

            else:
                state = 'password error'
    else:
        form = setPasswordForm()

    context = {
            'state': state,
             'user': user,
            'form': form
        }

    return render(request, 'management/set_password.html', context)

        # 下面是关于加入图书的部分
        # 首先就是权限管理，最后再统一看


# @user_passes_test(permission_check)
def add_book(request):
    user = request.user
    state = None
    if request.method == 'POST':
        form = addBookForm(request.POST)
        if form.is_valid():
            new_book = Book(
                    name=form.cleaned_data.get('name'),
                    author=form.cleaned_data.get('author'),
                    category=form.cleaned_data.get('category'),
                    price=form.cleaned_data.get('price'),
                    pub_date=form.cleaned_data.get('pub_date'),
            )
            new_book.save()
            state = 'success'
    else:
        form = addBookForm()

    context = {
        'state': state,
        'user': user,
        'form': form
    }
    return render(request, 'management/add_book.html', context)


# 下面应该是查看关于具体的书目列表的信息
# 我觉得在这里的思路应该是非常清晰的，用 category_list来表示左边的列表目录
# 用 book_list 来表示右边的书籍目录
# 用 query_category 来表示选择要查看的 category

def view_book_list(request):
    # 所以还是没有
    page = request.GET.get('page')
    user = request.user if request.user.is_authenticated() else None
    category_list = Book.objects.values_list('category', flat=True).distinct()
    query_category = request.POST.get('category', 'all')

    if not query_category or Book.objects.filter(category=query_category).count() == 0:
        query_category = 'all'
        book_list = Book.objects.all()
    else:
        book_list = Book.objects.filter(category=query_category)

    # 下面是关于搜索的情况
    if request.method == 'POST':
        keyword = request.POST.get('keyword', '')
        book_list = Book.objects.filter(name__contains=keyword)
    # 换言之，这里的 query_category 个人感觉不用也可以，只是还要在 模板文件里 看清楚

    # 关于分页，这里只能先按照它写的来，之后再看文档
    paginator = Paginator(book_list, 3)
    # 从当前页码中得到点击
    print(page)
    try:
        book_list = paginator.page(page)
    except PageNotAnInteger:
        book_list = paginator.page(1)
    except EmptyPage:
        book_list = paginator.page(num_pages)
    context = {
        'user': user,
        'category_list': category_list,
        'book_list': book_list,
        'query_category': query_category,
    }
    return render(request, 'management/view_book_list.html', context)


def detail(request):
    # 获取一个书籍的详细信息
    user = request.user if request.user.is_authenticated() else None
    # 这里可以用 key ，也可以用 if
    book_id = request.GET.get('id')
    if not book_id:
        return HttpResponseRedirect('/view_book_list')

    try:
        book = Book.objects.get(pk=book_id)
    except Book.DoesNotExist:
        return HttpResponseRedirect('/view_book_list')

    context = {
        'user': user,
        'book': book,
    }
    return render(request, 'management/detail.html', context)


# 在 add_image 之前应该还有一个权限检测
# @user_passes_test(permission_check)
def add_image(request):
    user = request.user
    user.myuser.permission
    state = None
    if request.method == 'POST':
        form = addImageForm(request.POST, request.FILES)
        if form.is_valid():
            try:
                # cleaned_data = form.cleaned_data
                new_image = Image(
                        name=form.cleaned_data.get('name'),
                        description=form.cleaned_data.get('description'),
                        image=request.FILES.get('image'),
                        book=Book.objects.get(pk=form.cleaned_data.get('book').id),
                )
                new_image.save()
            except Book.DoesNotExist:
                state = 'book not exist'
            else:
                state = 'success'
    else:
        form = addImageForm()

    context = {
        'user': user,
        'state': state,
        'book_list': Book.objects.all(),
        'form': form
    }

    return render(request, 'management/add_image.html', context)

# 好吧，完成基本的view,下面就是对应 url 以及模板的编写了  # Create your views here.
#@login_required
def edit(request,id):
	#book_id=request.GET.get('id')
	print(id)
	book = Book.objects.get(pk=id)
	print(book)
	if request.method == 'POST':
		book_form = BookEditForm(request.POST, instance=book)
		if book_form.is_valid():
			print('ok') 
			book_form.save()
	else:
		book_form=BookEditForm(instance=book)
	return render(request, 'management/edit.html', {'book_form':book_form})

zwLibraryManager/Library/templates/management/add_book.html
{% extends "management/base.html" %}
{% load staticfiles %}
{% block title %}添加图书{% endblock %}

{% block content %}

    <!-- 下面是关于 bootstrap 布局的部分-->
    <div class="container">

    {% if state == 'success' %}
        <div class="well">
            <h2 class="text-center text-success">添加成功</h2>
        </div>

        {% endif %}
    <form method="post" role="form" class="form-horizontal">
        {% csrf_token %}
        <h1 class="form-signin-heading text-center">添加图书</h1>

        <div class="form-group">
                        <label for="id_{{ form.name.name }}" class="col-md-3 control-label">{{ form.name.label }}</label>
                        <div class="col-md-9">
                            <input type="text" class="form-control" id="id_{{ form.name.name }}" required name="{{ form.name.name }}" autofocus>
                        </div>
        </div>

        <div class="form-group">
                        <label for="id_{{ form.pub_date.name }}" class="col-md-3 control-label">{{ form.pub_date.label }}</label>
                        <div class="col-md-9">
                            <input type="date" class="form-control" id="id_{{ form.pub_date.name }}" required name="{{ form.pub_date.name }}" autofocus>
                        </div>
        </div>

        <div class="form-group">
                        <label for="id_{{ form.price.name }}" class="col-md-3 control-label">{{ form.price.label }}</label>
                        <div class="col-md-9">
                            <input type="text" class="form-control" id="id_{{ form.price.name }}" required name="{{ form.price.name }}" autofocus>
                        </div>
        </div>

        <div class="form-group">
                        <label for="id_{{ form.author.name }}" class="col-md-3 control-label">{{ form.author.label }}</label>
                        <div class="col-md-9">
                            <input type="text" class="form-control" id="id_{{ form.author.name }}" required name="{{ form.author.name }}" autofocus>
                        </div>
        </div>

        <div class="form-group">
                        <label for="id_{{ form.category.name }}" class="col-md-3 control-label">{{ form.category.label }}</label>
                        <div class="col-md-9">
                            <input type="text" class="form-control" id="id_{{ form.category.name }}" required name="{{ form.category.name }}" autofocus>
                        </div>
        </div>

        <div class=" col-md-9"   >
        <button type="submit" value="submit" class="btn btn-default">提交</button>
        </div>


    </form>
    </div>
{% endblock %}

zwLibraryManager/Library/templates/management/add_image.html
{% extends "management/base.html" %}
{% load staticfiles %}
{% block title %}添加图片{% endblock %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
                {% if state == 'success' %}
                    <div class="well">
                        <h2 class="text-success text-center">添加成功</h2>
                    </div>
                {% elif state == 'error' %}
                    <div class="well">
                        <h2 class="text-danger text-center">添加失败</h2>
                    </div>
                {% endif %}

                <form method="post" role="form" class="form-horizontal" enctype="multipart/form-data">
                    {% csrf_token %}
                    <h1 class="form-signin-heading text-center">添加图片</h1>

                    <div class="form-group">
                        <label for="id_{{ form.name.name }}" class="col-md-3 control-label">{{ form.name.label }}</label>
                        <div class="col-md-9">
                            <input type="text" class="form-control" id="id_{{ form.name.name }}" required name="{{ form.name.name }}" autofocus>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="id_{{ form.description.name }}" class="col-md-3 control-label">{{ form.description.label }}</label>
                        <div class="col-md-9">
                            <input type="text" class="form-control" required name="{{ form.description.name }}" id="id_{{ form.description.name }}">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="id_{{ form.book.name }}" class="col-md-3 control-label">{{ form.book.label }}</label>
                        <div class="col-md-9">
                            <select name="{{ form.book.name }}" id="id_{{ form.book.name }}" class="form-control">
                                {% for book in book_list %}
                                    <option value="{{ book.id }}">{{ book.name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="id_{{ form.image.name }}" class="col-md-3 control-label">{{ form.image.label }}</label>
                        <div class="col-md-9">
                            <input type="file" id="id_{{ form.image.name }}" name="{{ form.image.name }}" class="form-control" required>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-4 col-md-offset-4">
                            <button class="btn btn btn-default btn-block" type="submit" value="submit">添加</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>


{% endblock %}

zwLibraryManager/Library/templates/management/base.html
{% load staticfiles %}
<!DOCTYPE html>
  <html lang="zh-cn">
    <head>
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta name="description" content="Library Management">
      <meta name="author" content="hzcortex">
        <title>{% block titile %}{% endblock %}</title>
   
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
     <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
    
    



    <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}">
    </script>

    </head>

    <body>
    <nav class="navbar navbar-default navbar-fixed-top">

        <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

        <a href="{% url 'homepage' %}" class="navbar-brand">Library</a>
    </div>>

       <div class="collapse navbar-collapse" id="navbar-collapse-basepage">
           <ul class="nav navbar-nav">
               <li><a href="{% url 'homepage' %}">主页</a></li>
               <!-- 这里是关于权限的部分 -->
               {% if user.myuser.permission > 1 %}
               <li><a href="{% url 'add_book' %}">添加图书</a></li>
               <li><a href="{% url 'add_image' %}">添加图片</a></li>
               <!-- 这里是结束权限的部分-->
               {% endif  %}
               <li><a href="{% url 'view_book_list'%}">查看图书</a></li>
           </ul>

           <ul class="nav navbar-nav navbar-right">
               {% if user %}
               <li>欢迎 {{ user.username }}</li>
                   <li><a href="{% url 'logout' %}">注销</a></li>
                   <li><a href="{% url 'set_password' %}">修改密码</a></li>
                   {% else %}
                   <li><a href="{% url 'register' %}">注册</a></li>
                   <li><a href="{% url 'login' %}">登陆</a></li>
               {% endif %}
           </div>
  </div>
    </nav>

    <!-- 下面是关于头部的部分，固定图片，先看它的使用，之后再看文档-->
    <header class="jumbotron subhead">
        <div class="container">
            <h1>图书馆管理系统</h1>
            <h3>知识改变命运</h3>
        </div>
    </header>

    {% block content %}{% endblock %}

    <!-- 下面是关于尾部的部分-->
    <footer class="footer" role="contentinfo">
        <div class="container">
            <p class="text-center">Power by Django</p>
            <p class="text-center"><a href="http://hzcortex.me">hzcortex</a></p>
        </div>
    </footer>

    <!-- 这里用了一个 javascript 的特性，增加 active_menu,非常棒的一个服务 -->
<script type="text/javascript">
    $('#{{active_menu}}').addClass("active");
</script>
    </body>
</html>

zwLibraryManager/Library/templates/management/detail.html
{% extends "management/base.html" %}
{% load staticfiles %}

{% block title %}书本情况{% endblock %}

{% block content %}
 <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="col-md-5">
                    {% if book.img_set.all %}
                        <div id="carousel-generic" class="carousel slide" data-ride="carousel">
                            <ol class="carousel-indicators">
                                {% for img in book.image_set.all %}
                                    <li data-target="#carousel-generic" data-slide-to="{{ forloop.counter0 }}"
                                        {% if forloop.first %}class="active"{% endif %}></li>
                                {% endfor %}
                            </ol>
                            <div class="carousel-inner" role="listbox">
                                {% for img in book.img_set.all %}
                                    <div {% if forloop.first %}class="item active"{% else %}class="item"{% endif %}>
                                        <img class="img-rounded" src="{% url 'media' img.img %}">
                                    </div>
                                {% endfor %}
                            </div>
                            <a class="left carousel-control" href="#carousel-generic" role="button" data-slide="prev">
                                <span class="glyphicon glyphicon-chevron-left"></span>
                            </a>
                            <a class="right carousel-control" href="#carousel-generic" role="button" data-slide="next">
                                <span class="glyphicon glyphicon-chevron-right"></span>
                            </a>
                        </div>
                    {% else %}
                        <p class="text-center">暂无图片</p>
                    {% endif %}
                </div>
                <div class="col-md-6 col-md-offset-1">
                    <h2 class="text-center">{{ book.name }}</h2>
                    <br>
                    <h3>作者：{{ book.author }}</h3>
                    <h3>类别：{{ book.category }}</h3>
                    <h3>出版日期：{{ book.publish_data|date:"Y-m-d" }}</h3>
                    <h3>价格：{{ book.price|floatformat:2 }}</h3>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

zwLibraryManager/Library/templates/management/index.html
{% extends "management/base.html" %}
{% load staticfiles %}

{% block title %}
图书管理
{% endblock %}

{% block content %}
dd
{% endblock %}

zwLibraryManager/Library/templates/management/login.html
{% extends "management/base.html" %}

{% load staticfiles %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">

<form class="form-horizontal" method="post" role="form"  >
    {% csrf_token %}
    <fieldset>

        {% for field in form %}
            {% if field.errors %}

                <div class="form-group has-error">
                    <label class="control-label">{{ field.label }}</label>
                    <div class="controls">{{ field }}
                        <span class="help-inline">
                            {% for error in  field.errors %}{{ error }}{% endfor %}
                        </span>
                    </div>
                </div>

            {% else %}

                <div class="form-group">
                    <label for="id_{{ field.name }}" class="col-sm-2 control-label">{{ field.label }}</label>
                    <div class="col-md-3 col-sm-10">
                    <input type="text" class="form-control" id="id_{{ field.name }}" name="{{ field.name }}">
                    </div>


                </div>

            {% endif %}
        {% endfor %}
    </fieldset>
    <div class=" col-sm-offset-2 col-sm-10"   >
        <button type="submit" value="login" class="btn btn-primary">登陆</button>
    </div>
</form>

<form class="form-horizontal">
  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">Email</label>
    <div class="col-sm-10">
      <input type="email" class="form-control" id="inputEmail3" placeholder="Email">
    </div>
  </div>
  <div class="form-group">
    <label for="inputPassword3" class="col-sm-2 control-label">Password</label>
    <div class="col-sm-10">
      <input type="password" class="form-control" id="inputPassword3" placeholder="Password">
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <div class="checkbox">
        <label>
          <input type="checkbox"> Remember me
        </label>
      </div>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-default">Sign in</button>
    </div>
  </div>
</form>

</div>

{% endblock %}

zwLibraryManager/Library/templates/management/register.html
{% extends "management/base.html" %}
{% load staticfiles %}

{% block title %}注册{% endblock %}

{% block content %}

<div class="container">
    <div class="row">

            <form class="form-horizontal" method="post" role="form"  >
    {% csrf_token %}
    <fieldset>
        {% for field in form %}
            {% if field.errors %}
                <div class="form-group has-error">
                    <label class="control-label">{{ field.label }}</label>
                    <div class="controls">{{ field }}
                        <span class="help-inline">
                            {% for error in  field.errors %}{{ error }}{% endfor %}
                        </span>
                    </div>
                </div>
            {% else %}
                <div class="form-group">
                    <label for="id_{{ field.name }}" class="col-sm-2 control-label">{{ field.label }}</label>
                    <div class="col-md-3 col-sm-10">
                    <input type="text" class="form-control" id="id_{{ field.name }}" name="{{ field.name }}">
                    </div>
                </div>
            {% endif %}
        {% endfor %}
    </fieldset>
    <div class=" col-sm-offset-2 col-sm-10"   >
        <button type="submit" value="register" class="btn btn-default">注册</button>
    </div>
</form>

    </div>
</div>
{% endblock %}

zwLibraryManager/Library/templates/management/set_password.html
{% extends "management/base.html" %}
{% load staticfiles %}

{% block title %}修改密码{% endblock %}

{% block content %}
<div class="container">

{% if state == 'password_error' %}
                    <div class="well">
                        <h2 class="text-danger text-center">密码错误</h2>
                    </div>
                {% elif state == 'repeat_error' %}
                    <div class="well">
                        <h2 class="text-warning text-center">密码重复错误</h2>
                    </div>
                {% elif state == 'empty' %}
                    <div class="well">
                        <h2 class="text-warning text-center">密码不能为空</h2>
                    </div>
                {% elif state == 'success' %}
                    <div class="well">
                        <h2 class="text-success text-center">修改成功</h2>
                    </div>
{% endif %}

<form method="post" role="form" class="form-horizontal">
        {% csrf_token %}
        <h1 class="form-signin-heading text-center">修改密码</h1>

        <div class="form-group">
                        <label for="id_{{ form.password_old.name }}" class="col-md-3 control-label">{{ form.password_old.label }}</label>
                        <div class="col-md-9">
                            <input type="text" class="form-control" id="id_{{ form.password_old.name }}" required name="{{ form.password_old.name }}" autofocus>
                        </div>
        </div>

        <div class="form-group">
                        <label for="id_{{ form.password_new.name }}" class="col-md-3 control-label">{{ form.password_new.label }}</label>
                        <div class="col-md-9">
                            <input type="text" class="form-control" id="id_{{ form.password_new.name }}" required name="{{ form.password_new.name }}" autofocus>
                        </div>
        </div>

        <div class="form-group">
                        <label for="id_{{ form.password_repeat.name }}" class="col-md-3 control-label">{{ form.password_repeat.label }}</label>
                        <div class="col-md-9">
                            <input type="text" class="form-control" id="id_{{ form.password_repeat.name }}" required name="{{ form.password_repeat.name }}" autofocus>
                        </div>
        </div>

    <div class=" col-md-9"   >
        <button type="submit" value="submit" class="btn btn-default">提交</button>
        </div>

    </form>
</div>
{% endblock %}